name: test_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ^3.24.3
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.63.0 
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  uuid: ^4.5.1




  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
