// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKtByBamN5kNeTKycpfnZDQYpHl4L8h60',
    appId: '1:124327773822:web:17fd886fa40a90ec3ffa2f',
    messagingSenderId: '124327773822',
    projectId: 'expense-tracker-4ffdb',
    authDomain: 'expense-tracker-4ffdb.firebaseapp.com',
    storageBucket: 'expense-tracker-4ffdb.firebasestorage.app',
    measurementId: 'G-HGE93NLFWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQontawC5_3swOoIWURUh4EuiJNDNMzM',
    appId: '1:124327773822:android:77e21a16c41cd4cc3ffa2f',
    messagingSenderId: '124327773822',
    projectId: 'expense-tracker-4ffdb',
    storageBucket: 'expense-tracker-4ffdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPz3dtNq02uaC6OATVQYOj2YLunKnxC4',
    appId: '1:124327773822:ios:25c469b5902332433ffa2f',
    messagingSenderId: '124327773822',
    projectId: 'expense-tracker-4ffdb',
    storageBucket: 'expense-tracker-4ffdb.firebasestorage.app',
    iosBundleId: 'com.example.testDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPz3dtNq02uaC6OATVQYOj2YLunKnxC4',
    appId: '1:124327773822:ios:25c469b5902332433ffa2f',
    messagingSenderId: '124327773822',
    projectId: 'expense-tracker-4ffdb',
    storageBucket: 'expense-tracker-4ffdb.firebasestorage.app',
    iosBundleId: 'com.example.testDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKtByBamN5kNeTKycpfnZDQYpHl4L8h60',
    appId: '1:124327773822:web:16a20f7262a678e03ffa2f',
    messagingSenderId: '124327773822',
    projectId: 'expense-tracker-4ffdb',
    authDomain: 'expense-tracker-4ffdb.firebaseapp.com',
    storageBucket: 'expense-tracker-4ffdb.firebasestorage.app',
    measurementId: 'G-CMCN5RN7LJ',
  );
}
